cd ~/Documents/CoachLens/coachlens && cat > app/sessions/page.js << 'EOF'
'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { createClient } from '../../lib/supabase';
import ReactMarkdown from 'react-markdown';

function SessionsContent() {
  const [sessions, setSessions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);
  const [coachName, setCoachName] = useState('');
  const supabase = createClient();
  const searchParams = useSearchParams();
  const coachId = searchParams.get('coach');

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) window.location.href = '/login';
      else fetchSessions(data.user.id);
    });
  }, []);

  const fetchSessions = async (userId) => {
    let query = supabase.from('sessions').select('*').eq('user_id', userId).order('created_at', { ascending: false });
    if (coachId) query = query.eq('coach_id', coachId);
    const { data } = await query;
    setSessions(data || []);
    if (coachId) {
      const { data: coach } = await supabase.from('coaches').select('name').eq('id', coachId).single();
      if (coach) setCoachName(coach.name);
    }
    setLoading(false);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  const handleDownloadPDF = async (session) => {
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 60;
    const maxWidth = pageWidth - margin * 2;
    let y = margin;
    doc.setFillColor(253, 246, 238);
    doc.rect(0, 0, pageWidth, 80, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(61, 43, 31);
    doc.text('Coach', margin, 50);
    doc.setTextColor(193, 127, 90);
    doc.text('Lens', margin + 72, 50);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(139, 115, 85);
    doc.text(formatDate(session.created_at), pageWidth - margin, 50, { align: 'right' });
    doc.setDrawColor(232, 213, 188);
    doc.setLineWidth(1);
    doc.line(margin, 80, pageWidth - margin, 80);
    y = 110;
    const lines = session.analysis.split('\n');
    for (const line of lines) {
      if (y > pageHeight - margin) {
        doc.addPage();
        doc.setFillColor(253, 246, 238);
        doc.rect(0, 0, pageWidth, 40, 'F');
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.setTextColor(139, 115, 85);
        doc.text('CoachLens - ICF PCC Coaching Assessment', margin, 25);
        doc.setDrawColor(232, 213, 188);
        doc.line(margin, 40, pageWidth - margin, 40);
        y = 65;
      }
      if (line.startsWith('# ')) {
        doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(61, 43, 31);
        const wrapped = doc.splitTextToSize(line.replace('# ', ''), maxWidth);
        doc.text(wrapped, margin, y); y += wrapped.length * 22 + 8;
      } else if (line.startsWith('## ')) {
        doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(61, 43, 31);
        const wrapped = doc.splitTextToSize(line.replace('## ', ''), maxWidth);
        y += 6; doc.text(wrapped, margin, y); y += wrapped.length * 18 + 4;
        doc.setDrawColor(232, 213, 188); doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y); y += 10;
      } else if (line.startsWith('### ')) {
        doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(92, 74, 54);
        const wrapped = doc.splitTextToSize(line.replace('### ', ''), maxWidth);
        y += 4; doc.text(wrapped, margin, y); y += wrapped.length * 15 + 4;
      } else if (line.startsWith('---')) {
        doc.setDrawColor(232, 213, 188); doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y); y += 12;
      } else if (line.trim() === '') {
        y += 6;
      } else {
        doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(92, 74, 54);
        const cleanLine = line.replace(/\*\*(.*?)\*\*/g, '$1');
        const wrapped = doc.splitTextToSize(cleanLine, maxWidth);
        doc.text(wrapped, margin, y); y += wrapped.length * 14 + 2;
      }
    }
    doc.setFont('helvetica', 'italic'); doc.setFontSize(8); doc.setTextColor(181, 160, 144);
    doc.text('Generated by CoachLens - coachlens-rho.vercel.app', pageWidth / 2, pageHeight - 30, { align: 'center' });
    doc.save('CoachLens-Session-' + new Date(session.created_at).toISOString().split('T')[0] + '.pdf');
  };

  const markdownStyles = {
    h1: { fontFamily: 'Georgia, serif', fontSize: 22, color: '#3D2B1F', marginTop: 24, marginBottom: 8 },
    h2: { fontFamily: 'Georgia, serif', fontSize: 18, color: '#3D2B1F', marginTop: 20, marginBottom: 6 },
    h3: { fontFamily: 'Georgia, serif', fontSize: 15, color: '#5C4A36', marginTop: 16, marginBottom: 4 },
    p: { fontSize: 14, color: '#5C4A36', lineHeight: 1.75, marginBottom: 12 },
    li: { fontSize: 14, color: '#5C4A36', lineHeight: 1.75, marginBottom: 4 },
    strong: { color: '#3D2B1F', fontWeight: 700 },
  };

  return (
    <main style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #FDF6EE 0%, #F5EDE0 100%)', padding: '40px 20px', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ maxWidth: 860, margin: '0 auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32 }}>
          <div>
            <h1 style={{ fontFamily: 'Georgia, serif', fontSize: 36, color: '#3D2B1F', margin: 0 }}>{coachName ? coachName + "'s Sessions" : 'My Sessions'}</h1>
            <p style={{ color: '#8B7355', fontSize: 14, marginTop: 4 }}>{coachName ? 'Viewing sessions for ' + coachName : 'Your coaching session history'}</p>
          </div>
          <div style={{ display: 'flex', gap: 12 }}>
            {coachId && <a href="/coaches" style={{ background: 'transparent', border: '1px solid #D9C9B3', color: '#8B7355', borderRadius: 12, padding: '10px 20px', fontSize: 14, fontWeight: 600, textDecoration: 'none' }}>My Coaches</a>}
            <a href="/" style={{ background: '#8B6240', color: '#FFF', borderRadius: 12, padding: '10px 20px', fontSize: 14, fontWeight: 700, textDecoration: 'none' }}>+ New Analysis</a>
          </div>
        </div>
        {loading && <p style={{ color: '#8B7355', textAlign: 'center' }}>Loading sessions...</p>}
        {!loading && sessions.length === 0 && (
          <div style={{ background: '#FFFAF5', border: '1px solid #E8D5BC', borderRadius: 20, padding: 48, textAlign: 'center' }}>
            <p style={{ color: '#8B7355', fontSize: 16, fontFamily: 'Georgia, serif' }}>No sessions yet</p>
            <p style={{ color: '#B5A090', fontSize: 14 }}>{coachName ? 'No sessions assigned to ' + coachName + ' yet' : 'Analyze your first coaching session to see it here'}</p>
            <a href="/" style={{ display: 'inline-block', marginTop: 16, background: '#8B6240', color: '#FFF', borderRadius: 12, padding: '10px 24px', fontSize: 14, fontWeight: 700, textDecoration: 'none' }}>Analyze a Session</a>
          </div>
        )}
        {!selected && sessions.map((session) => (
          <div key={session.id} onClick={() => setSelected(session)}
            style={{ background: '#FFFAF5', border: '1px solid #E8D5BC', borderRadius: 16, padding: '20px 24px', marginBottom: 12, cursor: 'pointer', transition: 'box-shadow 0.2s' }}
            onMouseEnter={e => e.currentTarget.style.boxShadow = '0 4px 16px rgba(100,70,40,0.12)'}
            onMouseLeave={e => e.currentTarget.style.boxShadow = 'none'}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <p style={{ color: '#3D2B1F', fontWeight: 700, fontSize: 15, margin: 0, fontFamily: 'Georgia, serif' }}>Session #{session.id}</p>
                <p style={{ color: '#8B7355', fontSize: 13, margin: '4px 0 0' }}>{formatDate(session.created_at)}</p>
              </div>
              <span style={{ color: '#C17F5A', fontSize: 13, fontWeight: 600 }}>View Report</span>
            </div>
            <p style={{ color: '#8B7355', fontSize: 12, margin: '10px 0 0', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{session.transcript.slice(0, 120)}...</p>
          </div>
        ))}
        {selected && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
              <button onClick={() => setSelected(null)} style={{ background: 'transparent', border: '1px solid #D9C9B3', borderRadius: 10, padding: '8px 16px', color: '#8B7355', fontSize: 13, cursor: 'pointer' }}>Back to sessions</button>
              <button onClick={() => handleDownloadPDF(selected)} style={{ background: '#8B6240', color: '#FFF', border: 'none', borderRadius: 10, padding: '8px 20px', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>Download PDF</button>
            </div>
            <div style={{ background: '#FFFAF5', border: '1px solid #E8D5BC', borderRadius: 20, padding: 28 }}>
              <p style={{ color: '#8B7355', fontSize: 13, marginBottom: 16 }}>{formatDate(selected.created_at)}</p>
              <ReactMarkdown components={{
                h1: ({children}) => <h1 style={markdownStyles.h1}>{children}</h1>,
                h2: ({children}) => <h2 style={markdownStyles.h2}>{children}</h2>,
                h3: ({children}) => <h3 style={markdownStyles.h3}>{children}</h3>,
                p: ({children}) => <p style={markdownStyles.p}>{children}</p>,
                li: ({children}) => <li style={markdownStyles.li}>{children}</li>,
                strong: ({children}) => <strong style={markdownStyles.strong}>{children}</strong>,
              }}>
                {selected.analysis}
              </ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}

export default function SessionsPage() {
  return (
    <Suspense fallback={<div style={{ padding: 40, textAlign: 'center', color: '#8B7355' }}>Loading...</div>}>
      <SessionsContent />
    </Suspense>
  );
}